<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27383" started-at="2018-09-02T09:53:35Z" finished-at="2018-09-02T09:54:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27383" started-at="2018-09-02T09:53:35Z" finished-at="2018-09-02T09:54:03Z">
      <class name="com.ranford.functionalities.TestExecution">
        <test-method status="PASS" signature="verify_launch()[pri:1, instance:com.ranford.functionalities.TestExecution@6536e911]" name="verify_launch" duration-ms="18524" started-at="2018-09-02T15:23:35Z" finished-at="2018-09-02T15:23:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_launch -->
        <test-method status="PASS" signature="verify_login()[pri:2, instance:com.ranford.functionalities.TestExecution@6536e911]" name="verify_login" duration-ms="6824" started-at="2018-09-02T15:23:54Z" finished-at="2018-09-02T15:24:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login -->
        <test-method status="SKIP" signature="createNewBranch(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:4, instance:com.ranford.functionalities.TestExecution@6536e911]" name="createNewBranch" duration-ms="0" started-at="2018-09-02T15:24:01Z" data-provider="branch" finished-at="2018-09-02T15:24:01Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerExceptionat org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)at org.testng.internal.Parameters.handleParameters(Parameters.java:706)at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: java.lang.NullPointerExceptionat Excel.Excel_Class.rcount(Excel_Class.java:38)at com.ranford.functionalities.Repository.excelContent(Repository.java:109)at com.ranford.functionalities.TestExecution.verify_excelContent(TestExecution.java:33)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)... 22 more]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewBranch -->
        <test-method status="PASS" signature="verify_logout()[pri:5, instance:com.ranford.functionalities.TestExecution@6536e911]" name="verify_logout" duration-ms="1808" started-at="2018-09-02T15:24:01Z" finished-at="2018-09-02T15:24:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_logout -->
      </class> <!-- com.ranford.functionalities.TestExecution -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
